### ISSUE TITLE
Unhandled Promise Rejection Warning.

### ISSUE THREAD

**Issue by Sysetup** [gera2ld/markmap-lib#5] opened 2020-04-15 00:14 UTC
Hi, when `markmap file.md` is executed the system reports this error:

```
(node:15195) UnhandledPromiseRejectionWarning: TypeError: token.children is not iterable
    at extractInline (/usr/lib/node_modules/markmap-lib/dist/index.js:29:29)
    at buildTree (/usr/lib/node_modules/markmap-lib/dist/index.js:202:25)
    at transform (/usr/lib/node_modules/markmap-lib/dist/index.js:212:14)
    at createMarkmap (/usr/lib/node_modules/markmap-lib/dist/index.js:241:16)
(node:15195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you fit any idea to fix it?
Regards and thank you for this tool, we look forward to using it.

**Comment by gera2ld** [comment] 2020-04-15 01:55
Maybe related to #4 ?

**Comment by gera2ld** [comment] 2020-04-17 09:52
Closing as duplicate of #4 . Feel free to reopen this if it still happens.

**Closed by gera2ld** 2020-04-17 09:52 UTC

**Comment by Sysetup** [comment] 2020-04-17 14:09
> Maybe related to #4 ?

That's correct. Thank you.
